(package "file-header"
         "0.1.2"
         "Highly customizable self design file header")

(website-url "https://github.com/jcs-elpa/file-header")
(keywords "convenience" "file" "header")

(package-file "file-header.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "28.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
